env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
ignorePatterns: "src/@types/*.ts"
overrides:
  - files:
      - "test/**"
    plugins:
      - "jest"
    extends:
      - "plugin:jest/recommended"
    env:
      jest/globals: true
    rules:
      jest/no-disabled-tests:
        - warn
      jest/no-identical-title:
        - error
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - 0
  quotes:
    - error
    - double
  semi:
    - error
    - always
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
