version: "3.8"
services:
  devmode:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: api-dev
    command: pnpm run dev
    environment:
      NODE_ENV: ${NODE_ENV}
      DOTENV_KEY: ${DOTENV_KEY}
    env_file:
      - .env
    restart: always
    ports:
      - "4500"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
