version: "3.9"
services:
  devmode:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: api-dev
    command: pnpm run dev
    environment:
      NODE_ENV: development
    env_file:
      - .env
    restart: always
    ports:
      - "8080:3500"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
