services:
  express-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: express-dev
    command: pnpm run dev
    environment:
      NODE_ENV: development
    env_file:
      - .env
    restart: always
    ports:
      - "3500:3500"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
  postgresql:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_PASSWORD: /run/secrets/db_password
    restart: always
    shm_size: 128mb
    ports:
      - "7532:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql

secrets:
  db_password:
    file: db_password.txt

volumes:
  postgresql-data:
