---
name: Run Tests
env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
  PORT: ${{ secrets.PORT }}

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  API-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install pnpm
        run: npm -g install pnpm

      - name: Setup Node environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Write secrets to env file
        run: |
          echo "CLIENT_ID=${CLIENT_ID}" > .env
          echo "CLIENT_SECRET=${CLIENT_SECRET}" >> .env
          echo "DATABASE_URL=${DATABASE_URL}" >>.env
          echo "JWT_SECRET=${JWT_SECRET}" >> .env
          echo "JWT_EXPIRES_IN=${JWT_EXPIRES_IN}" >> .env
          echo "PORT=${PORT}" >> .env

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run coverage test
        run: pnpm run test:cov

      - name: Upload to codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Approve a PR
        if: github.actor == 'dependabot[bot]'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
