---
name: Run Tests
env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
  MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  PORT: ${{ secrets.PORT }}

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  API-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Write secrets to env file
        run: |
          echo "JWT_SECRET=${JWT_SECRET}" > .env
          echo "JWT_EXPIRES_IN=${JWT_EXPIRES_IN}" >> .env
          echo "MONGO_COLLECTION=${MONGO_COLLECTION}" >> .env
          echo "MONGO_URI=${MONGO_URI}" >> .env
          echo "PORT=${PORT}" >> .env

      - name: Build Docker image
        run: docker build -t test-api --target test .

      - name: Run tests in Docker container
        run: docker run --env-file .env -it --rm --name run-api-test test-api
