---
name: Run Tests
env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
  MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  PORT: ${{ secrets.PORT }}

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  API-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Install pnpm
        run: npm -g install pnpm

      - name: Setup Node environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Write secrets to env file
        run: |
          echo "JWT_SECRET=${JWT_SECRET}" > .env
          echo "JWT_EXPIRES_IN=${JWT_EXPIRES_IN}" >> .env
          echo "MONGO_COLLECTION=${MONGO_COLLECTION}" >> .env
          echo "MONGO_URI=${MONGO_URI}" >> .env
          echo "PORT=${PORT}" >> .env

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run coverage test
        run: pnpm run test:cov

      - name: Upload to codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
