---
name: Deploy to production
env:
  DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Login to Docker Hub
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t fp-capstone-backend .
          docker tag fp-capstone-backend:latest ${DOCKER_USERNAME}/fp-capstone-backend:latest
          docker push ${DOCKER_USERNAME}/fp-capstone-backend:latest

      - name: Trigger Render deployment
        run: |
          curl -X POST -d {} ${DEPLOY_HOOK}
