---
name: Deploy to production

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  Deployment:
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t fp-capstone-backend .
          docker tag fp-capstone-backend:latest $DOCKER_USERNAME/fp-capstone-backend:latest
          docker push $DOCKER_USERNAME/fp-capstone-backend:latest

      - name: Trigger Render deployment
        run: |
          curl -X POST -d {} $DEPLOY_HOOK
