---
name: Deploy to production

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  Deployment:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Write secrets to env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env.production
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> .env.production
          echo "MONGO_COLLECTION=${{ secrets.MONGO_COLLECTION }}" >> .env.production
          echo "MONGO_URI= ${{ secrets.MONGO_URI }}" >> .env.production
          echo "PORT=${{ secrets.PORT }}" >> .env.production

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t fp-capstone-backend .
          docker tag fp-capstone-backend:latest $DOCKERHUB_USERNAME/fp-capstone-backend:latest
          docker push $DOCKERHUB_USERNAME/fp-capstone-backend:latest

      - name: Trigger Render deployment
        run: |
          curl -X POST -d {} "${{ secrets.DEPLOY_HOOK }}"
